/**
 * @file main.c
 * @brief Main application entry point for the Embedded MIDI Step Sequencer.
 *
 * This file initializes all hardware and software modules used by the
 * sequencer system and runs the foreground loop. The foreground loop is
 * responsible for scanning user inputs, processing non-time-critical events,
 * updating display outputs, and responding to flags generated by the timer
 * interrupt service routine.
 */
 
#include <stdint.h>
#include <stdbool.h>
#include <buttons.h>
#include <display7seg.h>

int main(void)
{
    while (1)
    {
    }
}